//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateProject) DeepCopyInto(out *CreateProject) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Shipyard != nil {
		in, out := &in.Shipyard, &out.Shipyard
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateProject.
func (in *CreateProject) DeepCopy() *CreateProject {
	if in == nil {
		return nil
	}
	out := new(CreateProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnDeploymentContext) DeepCopyInto(out *KeptnDeploymentContext) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnDeploymentContext.
func (in *KeptnDeploymentContext) DeepCopy() *KeptnDeploymentContext {
	if in == nil {
		return nil
	}
	out := new(KeptnDeploymentContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnDeploymentContext) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnDeploymentContextList) DeepCopyInto(out *KeptnDeploymentContextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnDeploymentContext, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnDeploymentContextList.
func (in *KeptnDeploymentContextList) DeepCopy() *KeptnDeploymentContextList {
	if in == nil {
		return nil
	}
	out := new(KeptnDeploymentContextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnDeploymentContextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnDeploymentContextSpec) DeepCopyInto(out *KeptnDeploymentContextSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnDeploymentContextSpec.
func (in *KeptnDeploymentContextSpec) DeepCopy() *KeptnDeploymentContextSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnDeploymentContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnDeploymentContextStatus) DeepCopyInto(out *KeptnDeploymentContextStatus) {
	*out = *in
	if in.LastAppliedHash != nil {
		in, out := &in.LastAppliedHash, &out.LastAppliedHash
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnDeploymentContextStatus.
func (in *KeptnDeploymentContextStatus) DeepCopy() *KeptnDeploymentContextStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnDeploymentContextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnProject) DeepCopyInto(out *KeptnProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnProject.
func (in *KeptnProject) DeepCopy() *KeptnProject {
	if in == nil {
		return nil
	}
	out := new(KeptnProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnProjectList) DeepCopyInto(out *KeptnProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnProjectList.
func (in *KeptnProjectList) DeepCopy() *KeptnProjectList {
	if in == nil {
		return nil
	}
	out := new(KeptnProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnProjectSpec) DeepCopyInto(out *KeptnProjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnProjectSpec.
func (in *KeptnProjectSpec) DeepCopy() *KeptnProjectSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnProjectStatus) DeepCopyInto(out *KeptnProjectStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnProjectStatus.
func (in *KeptnProjectStatus) DeepCopy() *KeptnProjectStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnScheduledExec) DeepCopyInto(out *KeptnScheduledExec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnScheduledExec.
func (in *KeptnScheduledExec) DeepCopy() *KeptnScheduledExec {
	if in == nil {
		return nil
	}
	out := new(KeptnScheduledExec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnScheduledExec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnScheduledExecList) DeepCopyInto(out *KeptnScheduledExecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnScheduledExec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnScheduledExecList.
func (in *KeptnScheduledExecList) DeepCopy() *KeptnScheduledExecList {
	if in == nil {
		return nil
	}
	out := new(KeptnScheduledExecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnScheduledExecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnScheduledExecSpec) DeepCopyInto(out *KeptnScheduledExecSpec) {
	*out = *in
	in.SequenceExecutionTemplate.DeepCopyInto(&out.SequenceExecutionTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnScheduledExecSpec.
func (in *KeptnScheduledExecSpec) DeepCopy() *KeptnScheduledExecSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnScheduledExecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnScheduledExecStatus) DeepCopyInto(out *KeptnScheduledExecStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnScheduledExecStatus.
func (in *KeptnScheduledExecStatus) DeepCopy() *KeptnScheduledExecStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnScheduledExecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequence) DeepCopyInto(out *KeptnSequence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequence.
func (in *KeptnSequence) DeepCopy() *KeptnSequence {
	if in == nil {
		return nil
	}
	out := new(KeptnSequence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnSequence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceExecution) DeepCopyInto(out *KeptnSequenceExecution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceExecution.
func (in *KeptnSequenceExecution) DeepCopy() *KeptnSequenceExecution {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnSequenceExecution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceExecutionList) DeepCopyInto(out *KeptnSequenceExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnSequenceExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceExecutionList.
func (in *KeptnSequenceExecutionList) DeepCopy() *KeptnSequenceExecutionList {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnSequenceExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceExecutionSpec) DeepCopyInto(out *KeptnSequenceExecutionSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceExecutionSpec.
func (in *KeptnSequenceExecutionSpec) DeepCopy() *KeptnSequenceExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceExecutionStatus) DeepCopyInto(out *KeptnSequenceExecutionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceExecutionStatus.
func (in *KeptnSequenceExecutionStatus) DeepCopy() *KeptnSequenceExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceList) DeepCopyInto(out *KeptnSequenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnSequence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceList.
func (in *KeptnSequenceList) DeepCopy() *KeptnSequenceList {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnSequenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceRefSpec) DeepCopyInto(out *KeptnSequenceRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceRefSpec.
func (in *KeptnSequenceRefSpec) DeepCopy() *KeptnSequenceRefSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceSpec) DeepCopyInto(out *KeptnSequenceSpec) {
	*out = *in
	in.Sequence.DeepCopyInto(&out.Sequence)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceSpec.
func (in *KeptnSequenceSpec) DeepCopy() *KeptnSequenceSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnSequenceStatus) DeepCopyInto(out *KeptnSequenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnSequenceStatus.
func (in *KeptnSequenceStatus) DeepCopy() *KeptnSequenceStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnSequenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnService) DeepCopyInto(out *KeptnService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnService.
func (in *KeptnService) DeepCopy() *KeptnService {
	if in == nil {
		return nil
	}
	out := new(KeptnService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeployment) DeepCopyInto(out *KeptnServiceDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeployment.
func (in *KeptnServiceDeployment) DeepCopy() *KeptnServiceDeployment {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnServiceDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeploymentList) DeepCopyInto(out *KeptnServiceDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnServiceDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeploymentList.
func (in *KeptnServiceDeploymentList) DeepCopy() *KeptnServiceDeploymentList {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnServiceDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeploymentPrerequisites) DeepCopyInto(out *KeptnServiceDeploymentPrerequisites) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeploymentPrerequisites.
func (in *KeptnServiceDeploymentPrerequisites) DeepCopy() *KeptnServiceDeploymentPrerequisites {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeploymentPrerequisites)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeploymentProgress) DeepCopyInto(out *KeptnServiceDeploymentProgress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeploymentProgress.
func (in *KeptnServiceDeploymentProgress) DeepCopy() *KeptnServiceDeploymentProgress {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeploymentProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeploymentSpec) DeepCopyInto(out *KeptnServiceDeploymentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeploymentSpec.
func (in *KeptnServiceDeploymentSpec) DeepCopy() *KeptnServiceDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceDeploymentStatus) DeepCopyInto(out *KeptnServiceDeploymentStatus) {
	*out = *in
	out.Prerequisites = in.Prerequisites
	out.DeploymentProgress = in.DeploymentProgress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceDeploymentStatus.
func (in *KeptnServiceDeploymentStatus) DeepCopy() *KeptnServiceDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceList) DeepCopyInto(out *KeptnServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceList.
func (in *KeptnServiceList) DeepCopy() *KeptnServiceList {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceSpec) DeepCopyInto(out *KeptnServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceSpec.
func (in *KeptnServiceSpec) DeepCopy() *KeptnServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnServiceStatus) DeepCopyInto(out *KeptnServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnServiceStatus.
func (in *KeptnServiceStatus) DeepCopy() *KeptnServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnShipyard) DeepCopyInto(out *KeptnShipyard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnShipyard.
func (in *KeptnShipyard) DeepCopy() *KeptnShipyard {
	if in == nil {
		return nil
	}
	out := new(KeptnShipyard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnShipyard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnShipyardList) DeepCopyInto(out *KeptnShipyardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnShipyard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnShipyardList.
func (in *KeptnShipyardList) DeepCopy() *KeptnShipyardList {
	if in == nil {
		return nil
	}
	out := new(KeptnShipyardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnShipyardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnShipyardSpec) DeepCopyInto(out *KeptnShipyardSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]KeptnShipyardStage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnShipyardSpec.
func (in *KeptnShipyardSpec) DeepCopy() *KeptnShipyardSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnShipyardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnShipyardStage) DeepCopyInto(out *KeptnShipyardStage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnShipyardStage.
func (in *KeptnShipyardStage) DeepCopy() *KeptnShipyardStage {
	if in == nil {
		return nil
	}
	out := new(KeptnShipyardStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnShipyardStatus) DeepCopyInto(out *KeptnShipyardStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnShipyardStatus.
func (in *KeptnShipyardStatus) DeepCopy() *KeptnShipyardStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnShipyardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnStage) DeepCopyInto(out *KeptnStage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnStage.
func (in *KeptnStage) DeepCopy() *KeptnStage {
	if in == nil {
		return nil
	}
	out := new(KeptnStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnStage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnStageList) DeepCopyInto(out *KeptnStageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeptnStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnStageList.
func (in *KeptnStageList) DeepCopy() *KeptnStageList {
	if in == nil {
		return nil
	}
	out := new(KeptnStageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeptnStageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnStageSpec) DeepCopyInto(out *KeptnStageSpec) {
	*out = *in
	if in.Sequence != nil {
		in, out := &in.Sequence, &out.Sequence
		*out = make([]KeptnSequenceRefSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnStageSpec.
func (in *KeptnStageSpec) DeepCopy() *KeptnStageSpec {
	if in == nil {
		return nil
	}
	out := new(KeptnStageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeptnStageStatus) DeepCopyInto(out *KeptnStageStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeptnStageStatus.
func (in *KeptnStageStatus) DeepCopy() *KeptnStageStatus {
	if in == nil {
		return nil
	}
	out := new(KeptnStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sequence) DeepCopyInto(out *Sequence) {
	*out = *in
	if in.TriggeredOn != nil {
		in, out := &in.TriggeredOn, &out.TriggeredOn
		*out = make([]Trigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]Task, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sequence.
func (in *Sequence) DeepCopy() *Sequence {
	if in == nil {
		return nil
	}
	out := new(Sequence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Task) DeepCopyInto(out *Task) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Task.
func (in *Task) DeepCopy() *Task {
	if in == nil {
		return nil
	}
	out := new(Task)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}
