apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnservices
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - keptn.operator.keptn.sh
  resources:
  - keptnprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-secrets
subjects:
- kind: ServiceAccount
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-get-configmaps
subjects:
- kind: ServiceAccount
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-projects
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
  labels:
    {{- include "keptn-gitops-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-gitops-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "keptn-gitops-operator.serviceAccountName" . }}-manage-services
  apiGroup: rbac.authorization.k8s.io
