# permissions for end users to view keptnservicelevelindicators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnservicelevelindicator-viewer-role
rules:
- apiGroups:
  - keptn.sh
  resources:
  - keptnservicelevelindicators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keptn.sh
  resources:
  - keptnservicelevelindicators/status
  verbs:
  - get
