---
# Deployment of our promotion-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-service
  namespace: keptn 
spec:
  selector:
    matchLabels:
      run: promotion-service
  replicas: 1
  template:
    metadata:
      labels:
        run: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: keptnsandbox/promotion-service:latest # Todo: Replace this with your image name
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            readOnlyRootFilesystem: false 
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
        - name: distributor
          image: keptn/distributor:0.9.0
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.promotion.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
              readOnly: false
      volumes:
      - name: tmp-volume
        emptyDir: { }
      serviceAccountName: keptn-promotion-service

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-promotion-service
  namespace: keptn

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: keptn
  name: keptn-promotion-service-read
rules:
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "secrets" ]
    verbs: [ "get" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: keptn
  name: keptn-promotion-service-read
subjects:
  - kind: ServiceAccount
    name: keptn-promotion-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-promotion-service-read

