# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/keptn.sh_keptnshipyards.yaml
- bases/keptn.sh_keptnprojects.yaml
- bases/keptn.sh_keptnsequenceexecutions.yaml
- bases/keptn.sh_keptnservices.yaml
- bases/keptn.sh_keptnstages.yaml
- bases/keptn.sh_keptnsequences.yaml
- bases/keptn.sh_keptnscheduledexecs.yaml
- bases/keptn.sh_keptnservicedeployments.yaml
- bases/keptn.sh_keptndeploymentcontexts.yaml
- bases/keptn.sh_keptninstances.yaml
- bases/keptn.sh_keptnservicelevelindicators.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_keptnshipyards.yaml
#- patches/webhook_in_keptnprojects.yaml
#- patches/webhook_in_keptnsequenceexecutions.yaml
#- patches/webhook_in_keptnservices.yaml
#- patches/webhook_in_keptnstages.yaml
#- patches/webhook_in_keptnsequences.yaml
#- patches/webhook_in_keptnscheduledexecs.yaml
#- patches/webhook_in_keptnservicedeployments.yaml
#- patches/webhook_in_keptndeploymentcontexts.yaml
#- patches/webhook_in_keptninstances.yaml
#- patches/webhook_in_keptnservicelevelindicators.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_keptnshipyards.yaml
#- patches/cainjection_in_keptnprojects.yaml
#- patches/cainjection_in_keptnsequenceexecutions.yaml
#- patches/cainjection_in_keptnservices.yaml
#- patches/cainjection_in_keptnstages.yaml
#- patches/cainjection_in_keptnsequences.yaml
#- patches/cainjection_in_keptnscheduledexecs.yaml
#- patches/cainjection_in_keptnservicedeployments.yaml
#- patches/cainjection_in_keptndeploymentcontexts.yaml
#- patches/cainjection_in_keptninstances.yaml
#- patches/cainjection_in_keptnservicelevelindicators.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
