---
apiVersion: "keptn.sh/v1"
kind: "KeptnInstance"
metadata:
  name: "default"
spec:
  apiUrl: "{{ .ApiUrl }}"
  tokenType: "{{ .ApiTokenType }}"
  apiToken: "rsa:{{ .EncToken }}"

---
apiVersion: "keptn.sh/v1"
kind: "KeptnProject"
metadata:
  name: "{{ .Project }}"
spec:
  repository: "{{ .UpstreamRepoUrl }}"
  username: "{{ .UpstreamRepoUsername }}"
  password: "rsa:{{ .EncUpstreamToken }}"
  defaultBranch: "{{ .UpstreamRepoBranch }}"