{{ range $stage := .Stages }}
---
apiVersion: "keptn.sh/v1"
kind: "KeptnStage"
metadata:
  name: "{{ $stage }}"
spec:
  project: "{{ $.Project }}"
  sequence:
    - type: "sequenceref"
      sequenceRef: "{{ $.Project }}-{{ $stage }}"
{{ end }}
